"""Generate the filled AI Usage Disclosure Form from template and docs/AI_DISCLOSURE.md.

Produces:
  submission/LangAI3.0_AI_Disclosure.docx
  submission/AI_Disclosure_SRMIST_SRM_Carrot.docx
"""
from pathlib import Path
import docx
from docx.shared import Pt, RGBColor
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = ROOT / "inputs" / "ai_disclosure.docx"
OUT_DEFAULT = ROOT / "submission" / "LangAI3.0_AI_Disclosure.docx"
OUT_NAMED = ROOT / "submission" / "AI_Disclosure_SRMIST_SRM_Carrot.docx"


def build_disclosure():
    doc = docx.Document(str(TEMPLATE))

    # Helper to add bold lead + normal text
    def set_p(p, lead_text, val_text):
        p.text = ""
        r1 = p.add_run(lead_text)
        r1.bold = True
        r2 = p.add_run(" " + val_text)
        r2.bold = False

    # 1. Team details
    # P3: Team Name
    # P4: Project / Product Name
    # P5: Organization
    # P6: Submission Date
    set_p(doc.paragraphs[3], "Team Name:", "SRM_Carrot")
    set_p(doc.paragraphs[4], "Project / Product Name:", "FORGE — Smart Guided Troubleshooting Engine")
    set_p(doc.paragraphs[5], "Organization / Institution (if any):", "SRM Institute of Science and Technology, Kattankulathur")
    set_p(doc.paragraphs[6], "Submission Date:", "2026-09-30")

    # 2. AI Usage Declaration
    # P9: Did your team use any Artificial Intelligence (AI) in developing this project?
    doc.paragraphs[9].text = ""
    r = doc.paragraphs[9].add_run("Did your team use any Artificial Intelligence (AI) in developing this project?  ")
    r.bold = True
    r_ans = doc.paragraphs[9].add_run("Yes")
    r_ans.bold = True
    r_ans.font.color.rgb = RGBColor(0x0F, 0x9D, 0x58)

    doc.paragraphs[10].text = "Yes, AI tools were used for development assistance, docstrings, boilerplate, and design trade-off exploration. The shipped production engine executes zero model calls at serve time (rules and pre-compiled atlas only, $0.00 cost, 0 external tokens)."

    # 3. Purpose of AI Usage (Brief Details)
    set_p(doc.paragraphs[13], "Idea generation / brainstorming:", "Yes — Architectural alternatives were discussed with an AI assistant before implementation (build-time compilation vs request-time generation).")
    set_p(doc.paragraphs[14], "Code generation or assistance:", "Yes — AI assistant used for boilerplate, docstrings, test scaffolding and refactoring suggestions.")
    set_p(doc.paragraphs[15], "UI / UX design:", "No — The deck uses the organisers' own template; figures are generated by our own code.")
    set_p(doc.paragraphs[16], "Content creation:", "Yes — AI assistant assisted with README and deck phrasing; all technical claims were verified against our own measurement harness.")
    set_p(doc.paragraphs[17], "Data analysis:", "No — All analysis is our own code (forge/eval.py); no AI was used to produce any reported number.")
    set_p(doc.paragraphs[18], "Testing / debugging:", "Yes — AI assistant helped localise three edge-case defects; the fixes and the tests are ours.")
    set_p(doc.paragraphs[19], "Other:", "Yes — Deck figure generation code (tools/make_figs.py) was written with AI assistance.")

    # 4. Feature Origin Classification
    features = [
        ("Compile/serve architecture", "Self-Generated",
         "Our own design decision, taken after rejecting per-request generation. AI was used to argue the trade-offs, not to propose the split."),
        ("SIIS markdown structure parser (forge/compile.py::parse_siis)", "Both",
         "We specified the grammar and the one-action-one-screen rule; AI assisted with the clause splitter and the protected-collocation table."),
        ("Constraint gates (forge/contract.py::audit_envelope)", "Self-Generated",
         "Derived line by line from the guide's section 4.1/4.2 rule list."),
        ("Catalog grammar parsing + target/polarity resolution (forge/catalog.py)", "Both",
         "We discovered the catalog's four description families by analysing all 578 entries ourselves; AI assisted with the regexes."),
        ("Precision gate (decline rather than guess)", "Self-Generated",
         "Our design decision, made because coverage without justification would inflate the reported number."),
        ("Intent signature + two-tier margin-gated cache (forge/nlp.py, forge/serve.py)", "Both",
         "The atom-synonym approach and the margin gate are ours; AI assisted with paraphrase template wording."),
        ("BM25 + hashed n-gram encoder", "Both",
         "Standard algorithms, implemented from published definitions with AI assistance on the vectorisation."),
        ("FastAPI service + Docker packaging", "Both",
         "AI-assisted boilerplate; endpoints and response envelope are ours."),
        ("Evaluation harness (forge/eval.py)", "Self-Generated",
         "We wrote the metrics to match the guide's Appendix C template and chose to report the unfavourable ablation row."),
        ("Test suite (tests/test_forge.py)", "Both",
         "Tests written to pin each claim in the README; AI assisted with the fuzz cases."),
        ("Deck, figures, demo script", "Both",
         "Structure and claims are ours; figure-drawing code and phrasing were AI-assisted."),
    ]

    # Find index of section 4 header
    p_feat_idx = -1
    for idx, p in enumerate(doc.paragraphs):
        if "4. Feature Origin Classification" in p.text:
            p_feat_idx = idx
            break

    # Find index of section 5 header
    p_sec5_idx = -1
    for idx, p in enumerate(doc.paragraphs):
        if "5. Ethical & Compliance Confirmation" in p.text:
            p_sec5_idx = idx
            break

    # Delete existing template placeholders between section 4 and section 5
    for p in doc.paragraphs[p_feat_idx + 1:p_sec5_idx]:
        p._p.getparent().remove(p._p)

    # Insert features right after section 4
    sec4_elem = doc.paragraphs[p_feat_idx]._p
    parent = sec4_elem.getparent()
    insert_after = sec4_elem

    for i, (fname, forigin, fdesc) in enumerate(features, 1):
        # Paragraph 1: Feature Name & Origin
        p1 = doc.add_paragraph()
        r1 = p1.add_run(f"Feature {i}: {fname}  —  ")
        r1.bold = True
        r2 = p1.add_run(f"[{forigin}]")
        r2.bold = True
        if forigin == "Self-Generated":
            r2.font.color.rgb = RGBColor(0x14, 0x28, 0xA0)
        else:
            r2.font.color.rgb = RGBColor(0x0F, 0x9D, 0x58)

        # Paragraph 2: Description
        p2 = doc.add_paragraph()
        rd_lead = p2.add_run("Description: ")
        rd_lead.bold = True
        p2.add_run(fdesc)

        # Spacing
        p_space = doc.add_paragraph()

        # Move new paragraphs into position
        parent.remove(p1._p)
        parent.remove(p2._p)
        parent.remove(p_space._p)

        insert_after.addnext(p1._p)
        p1._p.addnext(p2._p)
        p2._p.addnext(p_space._p)
        insert_after = p_space._p

    # Section 5: Ethical & Compliance Confirmation
    for p in doc.paragraphs:
        if "AI usage complies with guidelines and policies" in p.text:
            p.text = ""
            r = p.add_run("AI usage complies with guidelines and policies: ")
            r.bold = True
            r_val = p.add_run("Yes")
            r_val.bold = True
            r_val.font.color.rgb = RGBColor(0x0F, 0x9D, 0x58)
        elif "No proprietary or copyrighted data misused" in p.text:
            p.text = ""
            r = p.add_run("No proprietary or copyrighted data misused: ")
            r.bold = True
            r_val = p.add_run("I Agree")
            r_val.bold = True
            r_val.font.color.rgb = RGBColor(0x0F, 0x9D, 0x58)

    # Section 6: Declaration & Sign-Off
    for p in doc.paragraphs:
        if "Name of Team Representative:" in p.text:
            set_p(p, "Name of Team Representative:", "Vijval Parakkat")
        elif "Role:" in p.text:
            set_p(p, "Role:", "Team lead / engine implementation")
        elif "Signature:" in p.text:
            set_p(p, "Signature:", "Vijval Parakkat")
        elif "Date:" in p.text:
            set_p(p, "Date:", "2026-09-30")

    doc.save(str(OUT_DEFAULT))
    doc.save(str(OUT_NAMED))
    print(f"Generated AI disclosure forms:\n  -> {OUT_DEFAULT}\n  -> {OUT_NAMED}")


if __name__ == "__main__":
    build_disclosure()
